### ISSUE TITLE
for human-specific fine-tuning，I can't execute 

### ISSUE THREAD

**Issue by zhangtao22** [Wangt-CN/DisCo#24]
I set my dataset like the toy_dataset you provided. However, it can't execute. I encountered this problem
Original Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/DisCo/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py", line 569, in __getitem__
    raw_data = self.get_img_txt_pair(idx)
  File "/data/DisCo/dataset/tiktok_controlnet_t2i_imagevar_combine_specifcimg_web_upsquare.py", line 512, in get_img_txt_pair
    anno = list(open(anno_path))
FileNotFoundError: [Errno 2] No such file or directory: './719__242.png'

![image](https://github.com/Wangt-CN/DisCo/assets/35836562/b26e7fc6-79ba-44fb-a2c4-3a647a3e2b1d)

**Comment by zhangtao22** [comment]
anno_fname = os.path.join(dataset_prefix, vid + '__' + fid)
ref_mask_fname = os.path.join(dataset_prefix, self.ref_mask_path_web.format(vid, ref_fid))  # only choose 1st frame as ref frame
self.image_paths_list.append(image_fname)
self.ref_image_paths_list.append(ref_image_fname)
self.anno_pose_list.append(anno_pose_fname)
anno = list(open(anno_path))
img_key = json.loads(anno[0].strip())['image_key']
what does img_key use for?

**Comment by ljh0v0** [comment]
Hi, did u successfully run the human-specific fine-tuning?

**Comment by ppppppz** [comment]
> Hi, did u successfully run the human-specific fine-tuning? I'm also working on it now. If u don't mind, may be we can communicate .

Hi, did u continue to do this work? I'm also doing it, could u give me some advice plz?
